# Generated by Django 5.2.5 on 2025-08-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferred_category',
            new_name='preferred_job',
        ),
    ]
